export const comments = [
  {
    id: 1,
    articleId: 32,
    author: "Random User",
    body: "This is a very nice article",
    date: "Mon Jul 20 2020",
  },
  {
    id: 2,
    articleId: 92,
    author: "Random User",
    body: "This is a very nice article",
    date: "Mon Jul 20 2020",
  },
  {
    id: 3,
    articleId: 39,
    author: "Random User",
    body: "This is a very nice article",
    date: "Mon Jul 20 2020",
  },
  {
    id: 4,
    articleId: 5,
    author: "Random User",
    body: "This is a very nice article",
    date: "Mon Jul 20 2020",
  },
  {
    id: 5,
    articleId: 64,
    author: "Random User",
    body: "This is a very nice article",
    date: "Mon Jul 20 2020",
  },
  {
    id: 6,
    articleId: 3,
    author: "Random User",
    body: "This is a very nice article",
    date: "Mon Jul 20 2020",
  },
  {
    id: 7,
    articleId: 2,
    author: "Random User",
    body: "This is a very nice article",
    date: "Mon Jul 20 2020",
  },
  {
    id: 8,
    articleId: 23,
    author: "Random User",
    body: "This is a very nice article",
    date: "Mon Jul 20 2020",
  },
  {
    id: 9,
    articleId: 16,
    author: "Random User",
    body: "This is a very nice article",
    date: "Mon Jul 20 2020",
  },
  {
    id: 10,
    articleId: 32,
    author: "Random User",
    body: "This is a very nice article",
    date: "Mon Jul 20 2020",
  },
  {
    id: 11,
    articleId: 12,
    author: "Random User",
    body: "This is a very nice article",
    date: "Mon Jul 20 2020",
  },
  {
    id: 12,
    articleId: 12,
    author: "Random User",
    body: "This is a very nice article",
    date: "Tue Jul 21 2020",
  },
];
