export const queries = [
  {
    id: 1,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jul 21 2020",
    read: false,
  },
  {
    id: 2,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jul 22 2020",
    read: true,
  },
  {
    id: 3,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jun 20 2020",
    read: false,
  },
  {
    id: 4,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jul 20 2020",
    read: true,
  },
  {
    id: 5,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jul 20 2020",
    read: false,
  },
  {
    id: 6,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jul 25 2020",
    read: true,
  },
  {
    id: 7,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jun 26 2020",
    read: true,
  },
  {
    id: 8,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jul 1 2020",
    read: false,
  },
  {
    id: 9,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "April 20 2020",
    read: true,
  },
  {
    id: 10,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "May 22 2020",
    read: false,
  },
  {
    id: 11,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Sep 20 2020",
    read: true,
  },
  {
    id: 12,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "May 20 2020",
    read: false,
  },
  {
    id: 13,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jul 22 2020",
    read: false,
  },
  {
    id: 14,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jul 20 2020",
    read: false,
  },
  {
    id: 15,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jul 12 2020",
    read: false,
  },
  {
    id: 16,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jul 20 2020",
    read: false,
  },
  {
    id: 17,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jan 20 2020",
    read: true,
  },
  {
    id: 18,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jul 10 2020",
    read: false,
  },
  {
    id: 19,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Jul 20 2020",
    read: false,
  },
  {
    id: 20,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Oct 20 2020",
    read: false,
  },
  {
    id: 21,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Aug 20 2020",
    read: false,
  },
  {
    id: 22,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Feb 12 2020",
    read: false,
  },
  {
    id: 23,
    senderName: "John Doe",
    senderEmail: "test@random.email",
    subject: "Requesting node.js article",
    message: "I would like to see articles about node js",
    date: "Feb 20 2020",
    read: false,
  },
];
